### ISSUE TITLE
Incompatible with pyflakes version 2.5.0

### ISSUE THREAD

**Issue by corrafig** [Wilfred/pyimport#12]
Pyflakes 2.5.0 was released on Jul 30, 2022. Unfortunately they changed output a bit and hence pyimport doesn't work anymore. 

**How to reproduce**

1. Create a new file (my.py) with content: `import os`
2. Run `pyimport-remove-unused`

**Result**
1. Message: s-split: `Wrong type argument: stringp, nil`
2. Trace:
```Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  split-string(nil "\\." nil)
  s-split("\\." nil)
  pyimport--extract-unused-var("1")
  #f(compiled-function (it) #<bytecode 0x1184fa0077467323>)(("<stdin>" "1" "1" " 'os' imported but unused"))
  mapcar(#f(compiled-function (it) #<bytecode 0x1184fa0077467323>) (("<stdin>" "1" "1" " 'os' imported but unused")))
  pyimport-remove-unused()
  funcall-interactively(pyimport-remove-unused)
  command-execute(pyimport-remove-unused record)
  execute-extended-command(nil "pyimport-remove-unused" nil)
  funcall-interactively(execute-extended-command nil "pyimport-remove-unused" nil)
  command-execute(execute-extended-command)
```
Pyflakes difference between 2.4.0 and 2.5.0:

- 2.4.0: `my.py:1:1: 'os' imported but unused`
- 2.5.0: `my.py:1:1 'os' imported but unused`

**Comment by Wilfred** [comment]
Fixed in #13 I believe.
